id = "vscode-great-icons"
name = "VSCode Great Icons Theme"
version = "0.2.6"
schema_version = 1
authors = ["Jettison"]
description = "My personal modification of the VSCode great icons theme for Zed"
repository = "https://github.com/Jettiso/zed-vscode-jettison-icons"
